### ISSUE TITLE
BaseEntity's new behaviour disables own getters and setters

### ISSUE THREAD

**Issue by Aurielle** [Kdyby/Boilerplate#26]
Magické metody __get() a __set() jsou fajn, jenže přidáním podpory čtení/zápisu do protected properties PŘED vlastní detekci getterů/setterů totálně pohřbilo možnost ovlivnění vlastní hodnoty property getterem nebo setterem (nebo třeba provedením validace). Věřím, že to není záměrné. Mělo by to vyřešit prohození částí kódu v __get() a __set() (netestováno).

**Comment by fprochazka** [comment]
Díky.
