### ISSUE TITLE
$form->addDynamic does not work when it's first element in form

### ISSUE THREAD

**Issue by foglcz** [Kdyby/Boilerplate#28]
$form->addDynamic() does not work as expected... Use case:

``` php
for($i = 0; $i < 3; $i++) {
    $replicator = $form->addDynamic('users_' . $i, function (\Nette\ComponentModel\Container $user) {
        $user->addText('name', 'Jméno');
        $user->addText('surname', 'Příjmení');
    });
    $replicator->addSubmit('add_' . $i, 'Přidat usera ' . $i)
        ->setValidationScope(false)
        ->onClick[] = function(\Nette\Forms\Controls\SubmitButton $button) {
        $button->parent->createOne();
    };
}
```

Then it generates three buttons as expected. However, when clicking button with id 1 or 2 it works - when clicking the very first button, the user is visible only for the first load and does not persist.

It can be easily fixed by adding hidden input in front of the whole thing, that basically.. does nothing ;)

``` php
$form->addHidden('null');
for($i = 0; $i < 3; $i++) {
// ....
```

Not sure why this is happening though.

**Comment by fprochazka** [comment]
I think I've fixed it in 9d14619eb37 :) If not, please reopen.
