### ISSUE TITLE
BootstrapRenderer: inline checkboxy

### ISSUE THREAD

**Issue by carpi** [Kdyby/Boilerplate#40]
pokud chci pouzivat inline checkboxy, tak nemuzu protoze se label obaluje jeste divem, pokud jej odstranim, vse je v poradku

**Comment by fprochazka** [comment]
Implemented in 215d44b3844e9, use [CheckboxList](https://github.com/Kdyby/Framework/blob/master/libs/Kdyby/Forms/Controls/CheckboxList.php)
