### ISSUE TITLE
BootstrapRenderer not compatible with Replicator

### ISSUE THREAD

**Issue by Elijen** [Kdyby/Boilerplate#43]
Continuation from: http://forum.nette.org/cs/12046-kdyby-replicator-nefunguje-s-kdyby-bootstraprenderer

At Kdyby/FormsBootstrapRendererExtension@bce1db2 it is possible to add/remove Replicator container but it works just 1 time (even when the inputs are all filled).

At Kdyby/FormsBootstrapRendererExtension@373b285 the BootstrapRenderer seems not to work. Following exeption is thrown: "Argument 1 passed to Kdyby\Extension\Forms\BootstrapRenderer{closure}() must be an instance of Nette\Forms\Controls\BaseControl, instance of Nette\Iterators\Filter given" at line 267

``` php
/**
 * @param \Nette\Forms\Container $container
 * @return \Iterator
 */
public function findControls(Nette\Forms\Container $container = NULL)
{
    $container = $container ?: $this->form; // line 266
    return new Filter($container->getControls(), function (Controls\BaseControl $control) { //line 267
        return !$control->getOption('rendered');
    });
}
```

**Comment by fprochazka** [comment]
Can't reproduce. Could you please step by at #nettefw jabber chat and explain your problem in more details?

**Comment by fprochazka** [comment]
Bogus. [Solved by warning](http://addons.nette.org/cs/form-container-replicator?view=history#rev11).
