### ISSUE TITLE
BootstrapRenderer Html label for chechbox

### ISSUE THREAD

**Issue by TomPastyrik** [Kdyby/Boilerplate#44]
Hi, because compatibility with nette forms behavior I would allow creating \Nette\Utils\Html labels for chechboxes,
changing this

``` yaml
{label $name, class => 'checkbox'}{input $name}{$control->label->getText()}{/label}{$error}{$description}
```

to

``` yaml
{label $name, class => 'checkbox'}{input $name}{!$control->label->getHtml()}{/label}{$error}{$description}
```

should do it. 

Thanks for great tool by the way!

**Comment by fprochazka** [comment]
If this isn't resolved by [this](https://github.com/Kdyby/Framework/commit/2873052ffe7ee5f04eaa9e40392572f61fed85a8#L0R55), please reopen.
