### ISSUE TITLE
BootstrapRenderer: fails to render second form on page with macros

### ISSUE THREAD

**Issue by voda** [Kdyby/Boilerplate#45]
When rendering a control with macros from a  second form in template it throws a 'Component with name 'xxx' does not exist' exception. The `scopeVar` method called from `renderFormPart` return the old form.

Adding `{var $form = $_form = $presenter['xyzForm']}` right after the `{form}` macro _fixes_ the problem.

**Comment by fprochazka** [comment]
Thank you for the report!

**Comment by voda** [comment]
Thanks for the fix, updated just now and its working.

**Comment by fprochazka** [comment]
I'm glad to hear that!
