### ISSUE TITLE
Nette-addDynamic sandbox - problem with composer instalation

### ISSUE THREAD

**Issue by khorsky** [Kdyby/Boilerplate#50]
I'm not sure where to put this issue, I hope it fits here.

Situation: Nette-addDynamic sandbox cloned, I run composer install, autoload files were generated. When trying to run the sandbox, all I get was white screen. No error, no error in error log, nothing.

Finally I found this - in <project>/libs/composer/autoload_real.php I've to manually edit these lines to have Nette loader as the first one (composer generated Replicator loader on the first place):

``` php
require $vendorDir . '/nette/nette/Nette/loader.php';
require $vendorDir . '/kdyby/forms-replicator/Replicator.php';
```

I believe that the error came from the namespace used in Replicator, because the minimal Replicator file that broke it is

``` php
<?php

class Replicator extends \Nette\Forms\Container {
}
```

I tried to look in composer doc to find some clue how to influence the order, I haven't found it.

W7, PHP 5.4.6, 5.4.9, 5.3.19

**Comment by fprochazka** [comment]
Hi @BigCharlie, there was an error in composer autoloading configuration. I've fixed it HosipLan/Nette-addDynamic@35d48f342b7785c95, let me know if it persists.

**Comment by khorsky** [comment]
Unfortunately there are new problems. When cloned, composer install refuse to install: "The requested package nette/nette could not be found in any version" should be the main problem.

When I deleted composer.lock and run composer install, I get Latte CompileExtension: "Unknown macro {#} in ...\templates\@layout.latte:17"

I guess that nette recognizes # macro for block only in dev?

**Comment by fprochazka** [comment]
It should work by now.

**Comment by khorsky** [comment]
That's right.
